### Creat a user
POST http://localhost:9090/social-media/users
content-type: application/json

{
    "birthDate": {
        "year": 1987,
        "month": 02,
        "day": 06
    },
    "name": "Rimas",
    "mobileNumber": "+94718923456"
}

### Get users
GET http://localhost:9098/mediphix/patient

### Get a specific user
GET http://localhost:9090/social-media/users/5

### Get posts
GET http://localhost:9090/social-media/users/3/posts

### Create a post
POST http://localhost:9090/social-media/users/3/posts
content-type: application/json

{
    "description": "I want to learn Azure2",
    "tags": "azure,cloud,devops",
    "category": "education"
}

### Delete a user
DELETE http://localhost:9090/social-media/users/1

### Sentiment Analysis endpoint
POST http://localhost:9099/text-processing/api/sentiment

{
    "text": "I love this product"
}


### Save patient
POST http://localhost:9090/patient/registration

{
    "mobile_number": "0727654329",
    "first_name": "Ruwan",
    "last_name": "Rajakaruna",
    "nic": "987654321V",
    "birthday": "1999-05-15",
    "email": "kavindirana@gmail.com",
    "address": {
        "house_number": "56/7",
        "street": "Temple Road",
        "city": "Mount Lavinia",
        "province": "Western",
        "postal_code": "10370"
    },
    "allergies": ["Pollen", "Dust"],
    "special_notes": ["Requires follow-up on previous condition", "Has a history of asthma"]
}

